from typing import Iterator, Optional, Union

class MultiArg:
    def __init__(
        self,
        args: Union[list[str], str],
        fill: Optional[str] = ...,
        splitchar: str = ...,
    ) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, key: int) -> Optional[str]: ...
