from typing import Optional, Union

RangeSpec = Union[str, int, float, "Range"]

class Range:
    invert: bool
    start: float | int
    end: float | int

    def __init__(self, spec: Optional[RangeSpec] = ...) -> None: ...
    def __new__(cls, spec: Optional[RangeSpec] = ...) -> Range: ...
    def match(self, value: float | int) -> bool: ...
    def __contains__(self, value: float | int) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def violation(self) -> str: ...
