from typing import Literal, Union

from nagiosplugin.result import Results

class Summary:
    def ok(self, results: Results) -> str: ...
    def problem(self, results: Results) -> str: ...
    def verbose(self, results: Results) -> Union[str, list[str], tuple[str, ...]]: ...
    def empty(self) -> Literal["no check results"]: ...
