from typing import Generator

from nagiosplugin.cookie import Cookie

class LogTail:
    def __init__(self, path: str, cookie: Cookie) -> None: ...
    def __enter__(self) -> Generator[bytes, None, None]: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
