from io import StringIO
from logging import StreamHandler
from typing import List, Literal, Tuple

from nagiosplugin.check import Check

def filter_output(output: str, filtered: str) -> str: ...

class Output:

    ILLEGAL: Literal["|"] = ...

    logchan: StreamHandler[StringIO]
    verbose: int
    status: str
    out: List[str]
    warnings: List[str]
    longperfdata: List[str]

    def __init__(self, logchan: StreamHandler[StringIO], verbose: int = ...) -> None: ...
    def add(self, check: Check) -> None: ...
    def format_status(self, check: Check) -> str: ...
    def format_perfdata(self, check: Check, linebreak: int=...) -> str: ...
    def add_longoutput(self, text: str | List[str] | Tuple[str]) -> None: ...
    def __str__(self) -> str: ...
