from typing import List, Literal, Tuple

from nagiosplugin.check import Check

def filter_output(output: str, filtered: str) -> str: ...

class Output:
    ILLEGAL: Literal["|"] = ...
    def __init__(self, logchan, verbose: int = ...) -> None: ...
    def add(self, check: Check) -> None: ...
    def format_status(self, check: Check) -> str: ...
    def format_perfdata(self, check: Check, linebreak=...) -> str: ...
    def add_longoutput(self, text: str | List[str] | Tuple[str]) -> None: ...
    def __str__(self) -> str: ...
