from typing import NamedTuple

def worst(states: list[ServiceState]) -> ServiceState: ...

class ServiceState(NamedTuple("ServiceState", [("code", int), ("text", str)])):
    def __int__(self) -> int: ...
    def __str__(self) -> str: ...

class Ok(ServiceState):
    def __new__(cls) -> ServiceState: ...

class Warn(ServiceState):
    def __new__(cls) -> ServiceState: ...

class Critical(ServiceState):
    def __new__(cls) -> ServiceState: ...

class Unknown(ServiceState):
    def __new__(cls) -> ServiceState: ...
